# Generated by Django 4.2.5 on 2023-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='session_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
