# Generated by Django 4.2.5 on 2023-11-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_action_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.uploadedfile'),
        ),
    ]
