# Generated by Django 4.2.5 on 2023-12-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_remove_action_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='uploaded_file',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_page.uploadedfile'),
            preserve_default=False,
        ),
    ]
