# Generated by Django 4.2.5 on 2023-12-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_remove_template_actions_template_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='original_headers',
            field=models.JSONField(default=list),
        ),
    ]
