# Generated by Django 4.2.5 on 2023-12-23 20:15

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_template_original_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=main_page.models.get_upload_path, validators=[main_page.models.validate_file_extension]),
        ),
    ]
